version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    build:
      context: mysql/
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: asura_db
      POSTGRES_USER: projectasuras
      POSTGRES_PASSWORD: projectasuras
    ports:
      - "5432:5432"

networks:
  dev-network: